log:
  level: debug
  disable_sentry: true

db:
  url: postgres://auth:auth@localhost:5432/auth?sslmode=disable

listener:
  addr: :8000

jwt:
  secret_key: 0xbcb14d08dc1472b80f49eaf72f0873ac314a7146083bbf3694df8c3238949f2ec0971427f5509382a2812c700e541e328cd6ec65a1383c3ca435cdf55862dc4b
  access_expiration_time: 12h
  refresh_expiration_time: 24h

cookies:
  domain: "rarime.com"
  secure: true
  same_site: 4

auth_verifier:
  verification_key_path: "./auth_verification_key.json"
  disabled: true

passport_verifier:
  verification_key_path: "./passport_verification_key.json"
  allowed_age: 18
  allowed_identity_timestamp: 1715698750

root_verifier:
  rpc: evm_rpc_url
  contract: registration_contract_address
  request_timeout: 10s

sig_verifier:
  verification_key: hex_key_without_0x

points:
  url: http://127.0.0.1:8000/