openapi: 3.0.0
info:
  version: 1.0.0
  title: geo-auth-svc
  description: ''
servers:
  - url: 'https://api.orgs.app.stage.rarime.com/integrations/geo-auth-svc'
    description: RariMe Stage envirinment
paths:
  /integrations/geo-auth-svc/v1/authorize:
    post:
      tags:
        - Authorize
      summary: Authorize user
      description: |
        Authorize user by ZKP and receive JWT.
      operationId: authorize
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  $ref: '#/components/schemas/Authorize'
      responses:
        '200':
          description: OK
          content:
            application/vnd.api+json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    $ref: '#/components/schemas/Token'
        '400':
          $ref: '#/components/responses/invalidParameter'
        '401':
          description: Invalid proof
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
        '500':
          $ref: '#/components/responses/internalError'
  '/integrations/geo-auth-svc/v1/authorize/{nullifier}/challenge':
    get:
      tags:
        - Authorize
      summary: Request challenge
      description: |
        Request challenge to generate Query proof with
      operationId: challenge
      parameters:
        - $ref: '#/components/parameters/pathNullifier'
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    $ref: '#/components/schemas/Challenge'
        '400':
          $ref: '#/components/responses/invalidParameter'
        '500':
          $ref: '#/components/responses/internalError'
  /integrations/geo-auth-svc/v1/refresh:
    get:
      tags:
        - Authorize
      summary: Refresh JWT
      security:
        - JWTAuth: []
      description: |
        Issue new JWT based on refresh token
      operationId: refresh
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    $ref: '#/components/schemas/Token'
        '401':
          $ref: '#/components/responses/invalidAuth'
        '500':
          $ref: '#/components/responses/internalError'
  /integrations/geo-auth-svc/v1/validate:
    get:
      tags:
        - Authorize
      summary: Validate JWT
      security:
        - JWTAuth: []
      description: |
        Validates JWT provided in Bearer Header and returns decoded claims
      operationId: validate
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValidationResult'
        '401':
          $ref: '#/components/responses/invalidAuth'
  /integrations/geo-auth-svc/v2/authorize:
    post:
      tags:
        - Authorize
      summary: Authorize user V2
      description: |
        Authorize user by ZKP and receive JWT.
      operationId: authorizeV2
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  $ref: '#/components/schemas/Authorize'
      responses:
        '200':
          description: OK
          content:
            application/vnd.api+json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    $ref: '#/components/schemas/Token'
        '400':
          $ref: '#/components/responses/invalidParameter'
        '401':
          description: Invalid proof
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
        '500':
          $ref: '#/components/responses/internalError'
  /integrations/geo-auth-svc/v2/joinprogram:
    post:
      tags:
        - Passport verification
      summary: Join program
      security:
        - JWTAuth: []
      description: Join rewards program
      operationId: joinProgram
      parameters:
        - in: header
          name: Signature
          description: Signature of the request
          required: true
          schema:
            type: string
            pattern: '^[a-f0-9]{64}$'
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  $ref: '#/components/schemas/JoinProgram'
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    $ref: '#/components/schemas/Token'
        '400':
          $ref: '#/components/responses/invalidParameter'
        '401':
          $ref: '#/components/responses/invalidAuth'
        '403':
          description: Incorrect signature
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
        '409':
          description: AnonymousID/Nullifier already used by another Nullifier/AnonymousID
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
        '429':
          description: Passport already verified.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
        '500':
          $ref: '#/components/responses/internalError'
  /integrations/geo-auth-svc/v2/verifypassport:
    post:
      tags:
        - Passport verification
      summary: Verify passport
      security:
        - JWTAuth: []
      description: |
        Verify passport with ZKP.
        One passport can't be verified twice.
      operationId: verifyPassport
      parameters:
        - in: header
          name: Signature
          description: Signature of the request
          required: true
          schema:
            type: string
            pattern: '^[a-f0-9]{64}$'
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  $ref: '#/components/schemas/VerifyPassport'
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    $ref: '#/components/schemas/Token'
        '400':
          $ref: '#/components/responses/invalidParameter'
        '401':
          $ref: '#/components/responses/invalidAuth'
        '403':
          description: Incorrect signature
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
        '409':
          description: AnonymousID/Nullifier already used by another Nullifier/AnonymousID
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
        '429':
          description: Passport already proven.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
        '500':
          $ref: '#/components/responses/internalError'
components:
  schemas:
    Authorize:
      allOf:
        - $ref: '#/components/schemas/AuthorizeKey'
        - type: object
          x-go-is-request: true
          required:
            - attributes
          properties:
            attributes:
              required:
                - proof
              type: object
              properties:
                proof:
                  type: object
                  format: types.ZKProof
                  description: Query ZK passport verification proof.
    AuthorizeKey:
      type: object
      required:
        - id
        - type
      properties:
        id:
          type: string
          example: 0x123...abc
          pattern: '^0x[0-9a-fA-F]{64}$'
          description: User nullifier 32 bytes
        type:
          type: string
          enum:
            - authorize
    Challenge:
      allOf:
        - $ref: '#/components/schemas/ChallengeKey'
        - type: object
          required:
            - attributes
          properties:
            attributes:
              required:
                - challenge
              properties:
                challenge:
                  type: string
                  description: |
                    Base64 encoded challenge. Use it to generate Query ZK-proof.
                    Decode base64 string and convert into big-endian decimal number.
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
    ChallengeKey:
      type: object
      required:
        - id
        - type
      properties:
        id:
          type: string
          example: 0x123...abc
          pattern: '^0x[0-9a-fA-F]{64}$'
          description: User nullifier 32 bytes
        type:
          type: string
          enum:
            - challenge
    Claim:
      description: Authorized user personal data
      type: object
      required:
        - nullifier
        - is_verified
      properties:
        nullifier:
          type: string
          example: 0x123...abc
          pattern: '^0x[0-9a-fA-F]{64}$'
          description: Nullifier authorized with
        is_verified:
          type: bool
          example: true
          description: Whether the user has a scanned passport
    Errors:
      description: 'Standard JSON:API error'
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          description: Non empty array of errors occurred during request processing
          items:
            type: object
            required:
              - title
              - status
            properties:
              title:
                type: string
                description: 'Title is a short, human-readable summary of the problem'
                example: Bad Request
              detail:
                type: string
                description: Detail is a human-readable explanation specific to this occurrence of the problem
                example: Request body was expected
              status:
                type: integer
                description: Status is the HTTP status code applicable to this problem
                example: 400
                enum:
                  - 400
                  - 401
                  - 403
                  - 404
                  - 409
                  - 500
    JoinProgram:
      allOf:
        - $ref: '#/components/schemas/JoinProgramKey'
        - type: object
          x-go-is-request: true
          required:
            - attributes
          properties:
            attributes:
              required:
                - anonymous_id
              type: object
              properties:
                anonymous_id:
                  type: string
                  description: Unique identifier of the passport.
                  example: 2bd3a2532096fee10a45a40e444a11b4d00a707f3459376087747de05996fbf5
    JoinProgramKey:
      type: object
      required:
        - id
        - type
      properties:
        id:
          type: string
          description: Nullifier of the points owner
          example: 0x123...abc
          pattern: '^0x[0-9a-fA-F]{64}$'
        type:
          type: string
          enum:
            - join_program
    JWT:
      description: JWT token
      type: object
      required:
        - token
        - token_type
      properties:
        token:
          type: string
          description: Base64 encoded JWT
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        token_type:
          type: string
          enum:
            - access
            - refresh
    Token:
      allOf:
        - $ref: '#/components/schemas/TokenKey'
        - type: object
          required:
            - attributes
          properties:
            attributes:
              required:
                - access_token
                - refresh_token
              type: object
              properties:
                access_token:
                  $ref: '#/components/schemas/JWT'
                refresh_token:
                  $ref: '#/components/schemas/JWT'
    TokenKey:
      type: object
      required:
        - id
        - type
      properties:
        id:
          type: string
          example: 0x123...abc
          pattern: '^0x[0-9a-fA-F]{64}$'
          description: User nullifier 32 bytes
        type:
          type: string
          enum:
            - token
    ValidationResult:
      allOf:
        - $ref: '#/components/schemas/ValidationResultKey'
        - type: object
          required:
            - attributes
          properties:
            attributes:
              required:
                - claims
              type: object
              properties:
                claims:
                  type: array
                  items:
                    $ref: '#/components/schemas/Claim'
    ValidationResultKey:
      type: object
      required:
        - id
        - type
      properties:
        id:
          type: string
          example: 0x123...abc
          pattern: '^0x[0-9a-fA-F]{64}$'
          description: User nullifier 32 bytes
        type:
          type: string
          enum:
            - validation
    VerifyPassport:
      allOf:
        - $ref: '#/components/schemas/VerifyPassportKey'
        - type: object
          x-go-is-request: true
          required:
            - attributes
          properties:
            attributes:
              required:
                - anonymous_id
                - proof
              type: object
              properties:
                anonymous_id:
                  type: string
                  description: Unique identifier of the passport.
                  example: 2bd3a2532096fee10a45a40e444a11b4d00a707f3459376087747de05996fbf5
                proof:
                  type: object
                  format: types.ZKProof
                  description: |
                    Query ZK passport verification proof.
    VerifyPassportKey:
      type: object
      required:
        - id
        - type
      properties:
        id:
          type: string
          description: Nullifier of the points owner
          example: 0x123...abc
          pattern: '^0x[0-9a-fA-F]{64}$'
        type:
          type: string
          enum:
            - verify_passport
  responses:
    internalError:
      description: Internal server error
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
    invalidAuth:
      description: Failed to authorize JWT
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
    invalidParameter:
      description: One of the parameters is invalid. Refer to the response body for details.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
    notFound:
      description: Requested resource does not exist.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
  parameters:
    pageLimitParam:
      in: query
      name: 'page[limit]'
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 15
        description: Numbers of items per page to return.
    pageNumberParam:
      in: query
      name: 'page[number]'
      required: false
      schema:
        type: integer
      description: The number of a page to return.
    pathNullifier:
      in: path
      name: nullifier
      required: true
      schema:
        type: string
        example: 0x123...abc
        pattern: '^0x[0-9a-fA-F]{64}$'
        description: User nullifier 32 bytes
    sortingParam:
      in: query
      name: 'page[order]'
      required: false
      schema:
        type: string
        enum:
          - asc
          - desc
        default: desc
        description: 'Order of records on the page. If sortingParam is not specified, order of records is by default sorted by ID.'
  securitySchemes:
    JWTAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
